name: temp_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  zoom_tap_animation: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  http: ^1.1.0
  image_picker: ^1.0.1
  lottie: ^2.6.0
  pinput: ^3.0.0
  keyboard_dismisser: ^3.0.0
  mask_text_input_formatter: ^2.5.0
  url_launcher: ^6.1.12
  flutter_staggered_grid_view: ^0.7.0
  flutter_linkify: ^6.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
